### ISSUE TITLE
Xtream codes support

### ISSUE THREAD

**Issue by Miczys195** [tbrek/tbrek-kodi-repo#10]
Are you planning to add Xtream codes support

**Comment by tbrek** [comment]
I have no access to service supporting Xtream codes at the moment.

**Comment by Mariusz89B** [comment]
@tbrek tu masz kod dla xc.

`# Xtream Codes
                                        if ADDON.getSetting('archive_type') == '2':
                                            matches = re.compile('^(http[s]?://[^/]+)/(?:live/)?([^/]+)/([^/]+)/([^/\\.]+)(\\.m3u[8]?|\\.ts)?$')

                                            if matches.match(strmUrl):
                                                xcHost = matches.search(strmUrl).group(1)
                                                xcUsername = matches.search(strmUrl).group(2)
                                                xcPassword = matches.search(strmUrl).group(3)
                                                xcChannelId = matches.search(strmUrl).group(4)
                                                xcExtension = matches.search(strmUrl).group(5)

                                                if xcExtension is None:
                                                    m_isCatchupTSStream = True
                                                    xcExtension = ".ts"

                                                start = '{y}-{m}-{d}:{h}-{min}'.format(y=year, m=month, d=day, h=hour, min=minute)
                                                timeshift = duration + '/' + start

                                                try:
                                                    m_catchupSource = xcHost + "/timeshift/" + xcUsername + "/" + xcPassword + "/"+timeshift+"/" + xcChannelId + xcExtension
                                                except:
                                                    m_catchupSource = xcHost + "/timeshift/" + xcUsername + "/" + xcPassword + "/"+timeshift+"/" + xcChannelId + '.m3u8'

                                                strmUrl = m_catchupSource`

**Comment by ray2301** [comment]
XC links to catchup look like this:
http://{url}/timeshift/{username}/{password}/{duration}/{Y}-{m}-{d}:{H}-{M}-{S}/{channelnumber}.ts
for example, if streaming url is:
http://{url}/live/{username}/{password}/{channelnumber}.ts
or like this:
http://{url}/{username}/{password}/{channelnumber}

{duration} is calculated from EPG times in minutes (ie. 90). it's the lenght of the event
{Y}-{m}-{d}:{H}-{M}-{S} represents YEAR-MONTH-DATE:HOUR:MINUTE:SECOND (ie. 2024-05-19:14-57-00)

so if we have:
http://iptv.something/live/myuser/mypass/1745.ts
or
http://iptv.something/live/myuser/mypass/1745
as a link to the channel in the m3u,
the catchup URL for the EPG event starting at 17:00 and ending at 18:00 on the 19th May, 2024 would look like this:
http://iptv.something/timeshift/myuser/mypass/60/2024-05-19:17-00-00/1745.ts

in my m3u for iptvsimple, this imaginary channel would look like this:
#EXTINF:-1 catchup="xc" catchup-days="5" catchup-correction="0" tvg-id="HRT 1",HRT 1
http://iptv.something/live/myuser/mypass/1745.ts

or even like this if i'm using "1745.ts" for live tv because it's a HD version of the channel but using "489.ts" (different stream) for catchup since it has catchup but it is an SD version of the channel (that way i don't have to have 2 separate channels to watch catchup):
#EXTINF:-1 catchup="default" catchup-source="http://iptv.something/timeshift/myuser/mypass/{duration}/{Y}-{m}-{d}:{H}-{M}-{S}/489.ts" catchup-days="5" catchup-correction="0" group-title="News" tvg-id="HRT 1",HRT 1
http://iptv.something/live/myuser/mypass/1745.ts

i hope this makes sense to you if you want to persue the implementation of XC. i see that you're currently using some UTC times for your needs, i couldn't really figure out the code fully from a quick glance.

**Comment by alanmilinovic** [comment]
I would also like to have it supported. There is also a custom format, that can be used beside Tele and PlusX, but what are the parameters that can be used as there is no documentation about usage of this addon?

**Comment by tbrek** [comment]
> I would also like to have it supported. There is also a custom format, that can be used beside Tele and PlusX, but what are the parameters that can be used as there is no documentation about usage of this addon?

When custom is set it will append `archive_format` to the url
```
if (plugin.get_setting('external.m3u.archive', str) == "2"): # Custom
        archive_format = plugin.get_setting('external.m3u.custom', str).format(start,stop)
        url=url+archive_format
```

Although I have not added any params to be passed yet. Will sort it out in few days.

**Comment by alanmilinovic** [comment]
Great, thanks and happy New Year!

**Comment by alanmilinovic** [comment]
> > I would also like to have it supported. There is also a custom format, that can be used beside Tele and PlusX, but what are the parameters that can be used as there is no documentation about usage of this addon?
> 
> When custom is set it will append `archive_format` to the url
> 
> ```
> if (plugin.get_setting('external.m3u.archive', str) == "2"): # Custom
>         archive_format = plugin.get_setting('external.m3u.custom', str).format(start,stop)
>         url=url+archive_format
> ```
> 
> Although I have not added any params to be passed yet. Will sort it out in few days.

Any news on adding parameters to be passed? Thanks!
